development:
  sessions:
    default:
      database: acceptable_model_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: acceptable_model_test
      hosts:
        - localhost:27017